// MIT License
//
// Copyright (c) 2023-2025 Advanced Micro Devices, Inc. All rights reserved.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

/**
 * @file mini_regex.hpp
 * @brief A lightweight regex engine for ROCm profiling tools.
 *
 * @note This file was generated by an AI.
 *
 * Namespace: rocprofiler::common::regex
 *
 * Implements:
 *   - regex_match   (whole string must match)
 *   - regex_search  (find first substring match)
 *   - regex_replace (replace matches with replacement text)
 *
 * ## Supported Regex Syntax
 *
 * - Literals, escapes (\n, \t, \\)
 * - Character classes: [abc], ranges [a-z], negation [^], shorthands \d \D \w \W \s \S
 * - Dot (.)
 * - Anchors ^ and $
 * - Grouping ( … )
 * - Alternation |
 * - Quantifiers: *, +, ?, {m}, {m,}, {m,n}, with greedy/lazy variants (*?, +?, ??, {m,n}?)
 *
 * ## regex_replace Replacement Tokens
 *
 * - `$&` : whole match
 * - ``$`` : text before the match
 * - `$'` : text after the match
 * - (captures not supported yet; can be added later)
 */

#pragma once
#include <cassert>
#include <cctype>
#include <functional>
#include <limits>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace rocprofiler
{
namespace common
{
namespace regex
{

// ================================================================
// AST for regex
// ================================================================

struct Node
{
    enum Kind
    {
        LITERAL,
        DOT,
        CLASS,
        ANCHOR_BOL,
        ANCHOR_EOL,
        SEQ,
        ALT,
        QUANT
    } kind;
    char ch = 0;

    struct Class
    {
        std::function<bool(unsigned char)> pred;
    };
    std::optional<Class> cls;

    std::vector<Node> children;

    struct Quant
    {
        std::unique_ptr<Node> sub;
        size_t                min = 0, max = std::numeric_limits<size_t>::max();
        bool                  greedy = true;
    };
    std::unique_ptr<Quant> quant;

    Node(Kind k)
    : kind(k)
    {}
    Node(char c)
    : kind(LITERAL)
    , ch(c)
    {}
    static Node dot() { return Node(DOT); }
    // renamed from 'cls' to avoid clash with data member 'cls'
    static Node make_class(std::function<bool(unsigned char)> p)
    {
        Node n(CLASS);
        n.cls = Class{std::move(p)};
        return n;
    }
    static Node bol() { return Node(ANCHOR_BOL); }
    static Node eol() { return Node(ANCHOR_EOL); }
    static Node seq(std::vector<Node> v)
    {
        Node n(SEQ);
        n.children = std::move(v);
        return n;
    }
    static Node alt(std::vector<Node> v)
    {
        Node n(ALT);
        n.children = std::move(v);
        return n;
    }
    // renamed from 'quant' to avoid clash with data member 'quant'
    static Node make_quant(Node sub, size_t mi, size_t ma, bool greedy)
    {
        Node n(QUANT);
        n.quant         = std::make_unique<Quant>();
        n.quant->sub    = std::make_unique<Node>(std::move(sub));
        n.quant->min    = mi;
        n.quant->max    = ma;
        n.quant->greedy = greedy;
        return n;
    }
};

// ================================================================
// Parser
// ================================================================

struct Parser
{
    std::string_view pat;
    size_t           i = 0;
    explicit Parser(std::string_view p)
    : pat(p)
    {}

    bool end() const { return i >= pat.size(); }
    char peek() const { return end() ? '\0' : pat[i]; }
    char get() { return end() ? '\0' : pat[i++]; }
    bool eat(char c)
    {
        if(!end() && pat[i] == c)
        {
            ++i;
            return true;
        }
        return false;
    }
    static bool is_digit(char c) { return c >= '0' && c <= '9'; }

    std::vector<std::function<bool(unsigned char)>> special_preds;

    Node parse_escape_in_atom()
    {
        get();
        char e = get();
        if(e == '\0') return Node('\\');
        auto make_class = [&](auto p) { return Node::make_class(std::move(p)); };
        switch(e)
        {
            case 'd': return make_class([](unsigned char x) { return std::isdigit(x) != 0; });
            case 'D': return make_class([](unsigned char x) { return std::isdigit(x) == 0; });
            case 'w':
                return make_class([](unsigned char x) { return std::isalnum(x) || x == '_'; });
            case 'W':
                return make_class([](unsigned char x) { return !(std::isalnum(x) || x == '_'); });
            case 's': return make_class([](unsigned char x) { return std::isspace(x) != 0; });
            case 'S': return make_class([](unsigned char x) { return std::isspace(x) == 0; });
            case 'n': return Node('\n');
            case 't': return Node('\t');
            case 'r': return Node('\r');
            case 'f': return Node('\f');
            case 'v': return Node('\v');
            default: return Node(e);
        }
    }

    Node parse_class()
    {
        bool negate = false;
        if(eat('^')) negate = true;
        struct Range
        {
            unsigned char a, b;
        };
        std::vector<Range>         ranges;
        std::vector<unsigned char> singles;
        auto                       add_char = [&](unsigned char c) { singles.push_back(c); };
        bool                       first    = true;
        unsigned char              prev     = 0;
        bool                       has_prev = false;
        while(!end() && peek() != ']')
        {
            unsigned char c;
            if(eat('\\'))
            {
                char e = get();
                if(e == 'd' || e == 'D' || e == 'w' || e == 'W' || e == 's' || e == 'S')
                {
                    special_preds.push_back(
                        e == 'd'   ? [](unsigned char x) { return std::isdigit(x) != 0; }
                        : e == 'D' ? [](unsigned char x) { return std::isdigit(x) == 0; }
                        : e == 'w' ? [](unsigned char x) { return std::isalnum(x) || x == '_'; }
                        : e == 'W' ? [](unsigned char x) { return !(std::isalnum(x) || x == '_'); }
                        : e == 's' ? [](unsigned char x) { return std::isspace(x) != 0; }
                                   : [](unsigned char x) { return std::isspace(x) == 0; });
                    continue;
                }
                else
                    c = static_cast<unsigned char>(e);
            }
            else
                c = static_cast<unsigned char>(get());

            if(!first && c == '-' && peek() != ']' && has_prev)
            {
                unsigned char nxt;
                if(eat('\\'))
                    nxt = static_cast<unsigned char>(get());
                else
                    nxt = static_cast<unsigned char>(get());
                if(prev <= nxt)
                    ranges.push_back({prev, nxt});
                else
                    ranges.push_back({nxt, prev});
                has_prev = false;
                first    = false;
                continue;
            }
            else
            {
                if(has_prev) add_char(prev);
                prev     = c;
                has_prev = true;
            }
            first = false;
        }
        if(has_prev) add_char(prev);
        if(!eat(']')) throw std::runtime_error("Unterminated character class");
        auto rs       = std::move(ranges);
        auto ss       = std::move(singles);
        auto specials = std::move(special_preds);
        auto pred     = [rs, ss, specials, negate](unsigned char x) {
            bool in = false;
            for(auto& r : rs)
            {
                if(r.a <= x && x <= r.b)
                {
                    in = true;
                    break;
                }
            }
            if(!in)
            {
                for(auto c : ss)
                {
                    if(c == x)
                    {
                        in = true;
                        break;
                    }
                }
            }
            if(!in)
            {
                for(auto& sp : specials)
                {
                    if(sp(x))
                    {
                        in = true;
                        break;
                    }
                }
            }
            return negate ? !in : in;
        };
        return Node::make_class(pred);
    }

    struct RangeQ
    {
        size_t min, max;
        bool   ok;
    };
    RangeQ parse_brace_quant()
    {
        size_t save = i;
        if(!eat('{')) return {0, 0, false};
        auto read_num = [&]() -> std::optional<size_t> {
            if(end() || !is_digit(peek())) return std::nullopt;
            size_t v = 0;
            while(!end() && is_digit(peek()))
                v = v * 10 + (get() - '0');
            return v;
        };
        auto m = read_num();
        if(!m)
        {
            i = save;
            return {0, 0, false};
        }
        size_t mn = *m, mx = mn;
        if(eat('}')) return {mn, mx, true};
        if(!eat(','))
        {
            i = save;
            return {0, 0, false};
        }
        if(peek() == '}')
        {
            get();
            return {mn, std::numeric_limits<size_t>::max(), true};
        }
        auto n = read_num();
        if(!n || !eat('}'))
        {
            i = save;
            return {0, 0, false};
        }
        if(*n < mn)
            std::swap(mn, *n);
        else
            mx = *n;
        return {mn, mx, true};
    }

    Node parse_atom()
    {
        if(end()) throw std::runtime_error("Unexpected end in atom");
        char c = peek();
        if(c == '.')
        {
            get();
            return Node::dot();
        }
        if(c == '^')
        {
            get();
            return Node::bol();
        }
        if(c == '$')
        {
            get();
            return Node::eol();
        }
        if(c == '[')
        {
            get();
            return parse_class();
        }
        if(c == '(')
        {
            get();
            Node n = parse_alt();
            if(!eat(')')) throw std::runtime_error("Unmatched '('");
            return n;
        }
        if(c == '\\') return parse_escape_in_atom();
        get();
        return Node(c);
    }

    Node parse_atom_with_quant()
    {
        Node atom       = parse_atom();
        auto apply_lazy = [&](Node& q) {
            if(eat('?'))
                if(q.kind == Node::QUANT && q.quant) q.quant->greedy = false;
        };
        if(!end())
        {
            if(eat('*'))
            {
                Node q = Node::make_quant(std::move(atom), 0, std::numeric_limits<size_t>::max(), true);
                apply_lazy(q);
                return q;
            }
            if(eat('+'))
            {
                Node q = Node::make_quant(std::move(atom), 1, std::numeric_limits<size_t>::max(), true);
                apply_lazy(q);
                return q;
            }
            if(eat('?'))
            {
                Node q = Node::make_quant(std::move(atom), 0, 1, true);
                apply_lazy(q);
                return q;
            }
            auto br = parse_brace_quant();
            if(br.ok)
            {
                Node q = Node::make_quant(std::move(atom), br.min, br.max, true);
                apply_lazy(q);
                return q;
            }
        }
        return atom;
    }

    Node parse_seq()
    {
        std::vector<Node> v;
        while(!end())
        {
            char c = peek();
            if(c == ')' || c == '|') break;
            v.push_back(parse_atom_with_quant());
        }
        if(v.empty()) return Node::seq(std::vector<Node>{});
        if(v.size() == 1) return std::move(v[0]);
        return Node::seq(std::move(v));
    }

    Node parse_alt()
    {
        std::vector<Node> branches;
        branches.push_back(parse_seq());
        while(eat('|'))
            branches.push_back(parse_seq());
        if(branches.size() == 1) return std::move(branches[0]);
        return Node::alt(std::move(branches));
    }

    Node parse_all()
    {
        Node n = parse_alt();
        if(!end()) throw std::runtime_error("Trailing pattern content");
        return n;
    }
};

// ================================================================
// Matcher
// ================================================================

struct Matcher
{
    const Node&      root;
    std::string_view s;
    struct Key
    {
        const Node* node;
        size_t      idx;
        bool        operator==(const Key& o) const { return node == o.node && idx == o.idx; }
    };
    struct KeyHash
    {
        size_t operator()(const Key& k) const noexcept
        {
            return std::hash<const void*>()(k.node) ^ (std::hash<size_t>()(k.idx) << 1);
        }
    };
    std::unordered_map<Key, std::optional<size_t>, KeyHash> memo;

    Matcher(const Node& r, std::string_view sv)
    : root(r)
    , s(sv)
    {}

    std::optional<size_t> match(const Node* n, size_t i)
    {
        Key k{n, i};
        if(auto it = memo.find(k); it != memo.end()) return it->second;
        auto r = match_impl(n, i);
        memo.emplace(k, r);
        return r;
    }

    std::optional<size_t> match_impl(const Node* n, size_t i)
    {
        switch(n->kind)
        {
            case Node::LITERAL:
            {
                if(i < s.size() && (unsigned char) s[i] == (unsigned char) n->ch) return i + 1;
                return std::nullopt;
            }
            case Node::DOT:
            {
                if(i < s.size()) return i + 1;
                return std::nullopt;
            }
            case Node::CLASS:
            {
                if(i < s.size() && n->cls && n->cls->pred((unsigned char) s[i])) return i + 1;
                return std::nullopt;
            }
            case Node::ANCHOR_BOL:
            {
                if(i == 0) return i;
                return std::nullopt;
            }
            case Node::ANCHOR_EOL:
            {
                if(i == s.size()) return i;
                return std::nullopt;
            }
            case Node::SEQ:
            {
                size_t pos = i;
                for(const auto& ch : n->children)
                {
                    auto r = match(&ch, pos);
                    if(!r) return std::nullopt;
                    pos = *r;
                }
                return pos;
            }
            case Node::ALT:
            {
                for(const auto& br : n->children)
                {
                    auto r = match(&br, i);
                    if(r) return r;
                }
                return std::nullopt;
            }
            case Node::QUANT:
            {
                const auto&         q = *n->quant;
                std::vector<size_t> ends;
                ends.push_back(i);
                size_t pos = i, count = 0;
                while(count < q.max)
                {
                    auto r = match(q.sub.get(), pos);
                    if(!r) break;
                    if(*r == pos) break;  // zero-length guard
                    pos = *r;
                    ++count;
                    ends.push_back(pos);
                    if(pos > s.size()) break;
                }
                if(q.greedy)
                {
                    for(size_t k = ends.size(); k-- > 0;)
                    {
                        if(k < q.min) continue;
                        return ends[k];
                    }
                }
                else
                {
                    for(size_t used = 0; used < ends.size(); ++used)
                    {
                        if(used < q.min) continue;
                        return ends[used];
                    }
                }
                return std::nullopt;
            }
        }
        return std::nullopt;
    }

    bool full_match()
    {
        auto r = match(&root, 0);
        return r && *r == s.size();
    }

    std::optional<std::pair<size_t, size_t>> find_first()
    {
        for(size_t pos = 0; pos <= s.size(); ++pos)
        {
            auto end = match(&root, pos);
            if(end) return std::make_pair(pos, *end);
        }
        return std::nullopt;
    }
};

// ================================================================
// Public APIs
// ================================================================

inline bool
regex_match(std::string_view text, std::string_view pattern)
{
    Parser  P(pattern);
    Node    ast     = P.parse_all();
    // Avoid initializer_list to prevent copying non-copyable Node
    std::vector<Node> wrap_children;
    wrap_children.push_back(Node::bol());
    wrap_children.push_back(std::move(ast));
    wrap_children.push_back(Node::eol());
    Node    wrapped = Node::seq(std::move(wrap_children));
    Matcher M(wrapped, text);
    return M.full_match();
}

inline bool
regex_search(std::string_view text, std::string_view pattern)
{
    Parser  P(pattern);
    Node    ast = P.parse_all();
    Matcher M(ast, text);
    return M.find_first().has_value();
}

inline bool
regex_search(std::string_view text,
             std::string_view pattern,
             size_t&          match_begin,
             size_t&          match_end)
{
    Parser  P(pattern);
    Node    ast = P.parse_all();
    Matcher M(ast, text);
    if(auto r = M.find_first())
    {
        match_begin = r->first;
        match_end   = r->second;
        return true;
    }
    return false;
}

/**
 * @brief Replace occurrences of pattern in text with replacement.
 *
 * Supports:
 *   - `$&` : whole match
 *   - ``$`` : prefix before the match
 *   - `$'` : suffix after the match
 *
 * Example:
 *   regex_replace("abc123xyz", "\\d+", "[$&]") -> "abc[123]xyz"
 */
inline std::string
regex_replace(std::string_view text, std::string_view pattern, std::string_view replacement)
{
    Parser P(pattern);
    Node   ast = P.parse_all();

    std::string result;
    size_t      search_start = 0;
    while(search_start <= text.size())
    {
        Matcher M(ast, text.substr(search_start));
        if(auto r = M.find_first())
        {
            size_t b = search_start + r->first;
            size_t e = search_start + r->second;

            // append prefix
            result.append(text.substr(search_start, b - search_start));

            // expand replacement
            for(size_t i = 0; i < replacement.size(); ++i)
            {
                if(replacement[i] == '$' && i + 1 < replacement.size())
                {
                    char nxt = replacement[i + 1];
                    if(nxt == '&')
                    {
                        result.append(text.substr(b, e - b));
                        ++i;
                        continue;
                    }
                    if(nxt == '`')
                    {
                        result.append(text.substr(0, b));
                        ++i;
                        continue;
                    }
                    if(nxt == '\'')
                    {
                        result.append(text.substr(e));
                        ++i;
                        continue;
                    }
                }
                result.push_back(replacement[i]);
            }

            search_start = e;
        }
        else
        {
            result.append(text.substr(search_start));
            break;
        }
    }
    return result;
}

}  // namespace regex
}  // namespace common
}  // namespace rocprofiler

// Global forwards for convenience
inline bool
regex_match(std::string_view s, std::string_view p)
{
    return rocprofiler::common::regex::regex_match(s, p);
}
inline bool
regex_search(std::string_view s, std::string_view p)
{
    return rocprofiler::common::regex::regex_search(s, p);
}
inline bool
regex_search(std::string_view s, std::string_view p, size_t& b, size_t& e)
{
    return rocprofiler::common::regex::regex_search(s, p, b, e);
}
inline std::string
regex_replace(std::string_view s, std::string_view p, std::string_view r)
{
    return rocprofiler::common::regex::regex_replace(s, p, r);
}
