name: AqlProfile Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'projects/aqlprofile/**'
      - '!projects/aqlprofile/*.md'
      - '!projects/aqlprofile/CODEOWNERS'
      - '!projects/aqlprofile/source/docs/**'
      - '.github/workflows/aqlprofile-continuous_integration.yml'
  pull_request:
    paths:
      - 'projects/aqlprofile/**'
      - '!projects/aqlprofile/*.md'
      - '!projects/aqlprofile/CODEOWNERS'
      - '!projects/aqlprofile/source/docs/**'
      - '.github/workflows/aqlprofile-continuous_integration.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # TODO(jrmadsen): replace LD_RUNPATH_FLAG, GPU_TARGETS, etc. with internal handling in cmake
  PATH: "/usr/bin:$PATH"
  navi3_EXCLUDE_TESTS_REGEX: ""
  vega20_EXCLUDE_TESTS_REGEX: ""
  mi200_EXCLUDE_TESTS_REGEX: ""
  mi300_EXCLUDE_TESTS_REGEX: ""
  mi300a_EXCLUDE_TESTS_REGEX: ""
  mi325_EXCLUDE_TESTS_REGEX: ""
  navi4_EXCLUDE_TESTS_REGEX: ""
  navi3_EXCLUDE_LABEL_REGEX: ""
  vega20_EXCLUDE_LABEL_REGEX: ""
  mi200_EXCLUDE_LABEL_REGEX: ""
  mi300_EXCLUDE_LABEL_REGEX: ""
  mi300a_EXCLUDE_LABEL_REGEX: ""
  mi325_EXCLUDE_LABEL_REGEX: ""
  navi4_EXCLUDE_LABEL_REGEX: ""

jobs:
  core-deb:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      fail-fast: false
      matrix:
        system: [
          {gpu: 'navi4', runner: 'rocprofiler-navi4-dind', os: 'ubuntu-22.04', build-type: 'RelWithDebInfo', therock-s3: "gfx120X"},
          {gpu: 'navi3', runner: 'rocprofiler-navi3-dind', os: 'ubuntu-22.04', build-type: 'RelWithDebInfo', therock-s3: "gfx110X"},
          {gpu: 'mi325', runner: 'linux-mi325-1gpu-ossci-rocm', os: 'ubuntu-22.04', build-type: 'RelWithDebInfo', therock-s3: "gfx94X"}
        ]

    runs-on: ${{ matrix.system.runner }}
    container:
      image: ubuntu:22.04
      env:
        DEBIAN_FRONTEND: noninteractive
      options: --privileged

    permissions:
      contents: read
      pull-requests: write

    # define this for containers
    env:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
      GPU_RUNNER: ${{ matrix.system.gpu }}

    steps:
    - name: Install Latest ROCm
      shell: bash
      working-directory: /tmp
      run: |
        apt-get update
        apt-get install -y curl wget gpg python3 python3-pip build-essential coreutils software-properties-common
        mkdir --parents --mode=0755 /etc/apt/keyrings
        wget https://repo.radeon.com/rocm/rocm.gpg.key -O - | gpg --dearmor | tee /etc/apt/keyrings/rocm.gpg > /dev/null
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/rocm/apt/7.0_rc1 jammy main" | tee /etc/apt/sources.list.d/rocm.list
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/rocm.gpg] https://repo.radeon.com/amdgpu/latest/ubuntu jammy main" | tee /etc/apt/sources.list.d/amdgpu.list
        echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | tee /etc/apt/preferences.d/rocm-pin-600
        add-apt-repository ppa:git-core/ppa
        apt-get update
        apt-get install -y git rocm-llvm-dev
        python3 -m pip install awscli
        export PATH=/usr/local/bin:~/.local/bin:$PATH
        KEY=$(aws s3api list-objects-v2 \
          --bucket therock-nightly-tarball \
          --no-sign-request \
          --output json \
          --query "sort_by(Contents[?contains(Key, '${{ matrix.system.therock-s3 }}')], &LastModified)[-1].Key")
        KEY=${KEY//\"/}
        test -n "$KEY" || { echo "No ${{ matrix.system.therock-s3 }} tarball found"; exit 1; }
        aws s3 cp "s3://therock-nightly-tarball/${KEY}" rocm.tar.gz --no-sign-request
        ls -lh rocm.tar.gz
        echo "Downloaded: ${KEY}"
        tar -xf *.tar.gz -C /opt/rocm-7.0.0
        ln -s /opt/rocm-7.0.0 /opt/rocm

    - uses: actions/checkout@v5
      with:
        sparse-checkout: projects/aqlprofile
        set-safe-directory: true

    - name: Install requirements
      timeout-minutes: 10
      shell: bash
      run: |
        git config --global --add safe.directory '*'
        apt-get update
        apt-get install -y build-essential cmake g++-11 g++-12 python3-pip libgtest-dev libgmock-dev
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 10 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
        update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 20 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12

    - name: List Files
      shell: bash
      run: |
        echo "PATH: ${PATH}"
        echo "LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}"
        which-realpath() { echo -e "\n$1 resolves to $(realpath $(which $1))"; echo "$($(which $1) --version &> /dev/stdout | head -n 1)"; }
        for i in python3 git cmake ctest gcc g++ gcov; do which-realpath $i; done
        cat /opt/rocm/.info/version
        ls -la
        pwd

    - name: Special Requirements
      shell: bash
      run: |
          echo 'CMAKE_HIP_PLATFORM=amd' >> $GITHUB_ENV
          echo 'HIP_PLATFORM=amd' >> $GITHUB_ENV
          echo 'HIP_RUNTIME=rocclr' >> $GITHUB_ENV
          echo 'HIP_COMPILER=amdclang++' >> $GITHUB_ENV
          echo 'LLVM_PATH=/opt/rocm/llvm' >> $GITHUB_ENV
          echo 'CMAKE_PREFIX_PATH=/opt/rocm' >> $GITHUB_ENV

    - name: Configure, Build, and Test
      timeout-minutes: 30
      shell: bash
      run:
        LD_LIBRARY_PATH=$(pwd)/build:/opt/rocm/lib:$LD_LIBRARY_PATH
        PATH=/opt/rocm/bin:$PATH
        /usr/bin/ctest --output-on-failure -VV -DCTEST_SOURCE_DIRECTORY="$(pwd)"
          -DCTEST_BINARY_DIRECTORY="$(pwd)/build" -DAQLPROFILE_BUILD_NUM_JOBS="16" -DCTEST_SITE="$(hostname)"
          -DCTEST_BUILD_NAME=PR_${{ github.ref_name }}_${{ github.repository }}-${{ matrix.system.os }}-${{ matrix.system.gpu }}-core
          -DCMAKE_CTEST_ARGUMENTS=""
          -DAQLPROFILE_BUILD_TESTS=ON
          -DAQLPROFILE_EXTRA_CONFIGURE_ARGS=""
          -S $(pwd)/projects/aqlprofile/dashboard.cmake

  core-rpm:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      fail-fast: false
      matrix:
        system: [
          {gpu: 'mi325', os: 'rhel-9.1', build-type: 'RelWithDebInfo', container: ''},
          {gpu: 'mi325', os: 'sles-15.4', build-type: 'RelWithDebInfo', container: ''}
        ]

    runs-on: linux-mi325-1gpu-ossci-rocm
    container:
      image: rocm/rocprofiler-private:${{ matrix.system.os }}
      credentials:
        username: ${{ secrets.ROCPROFILER_AZURE_CI_USER }}
        password: ${{ secrets.ROCPROFILER_AZURE_CI_PASS }}
      options: --privileged

    permissions:
      contents: read
      pull-requests: write

    # define this for containers
    env:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
      GPU_RUNNER: ${{ matrix.system.gpu }}

    steps:
    - name: Install Latest ROCm
      shell: bash
      working-directory: /tmp
      run: |
        python3 -m pip install --upgrade pip pipx
        python3 -m pipx install awscli
        python3 -m pipx ensurepath
        source ~/.bashrc
        KEY=$(aws s3api list-objects-v2 \
          --bucket therock-nightly-tarball \
          --no-sign-request \
          --output json \
          --query "sort_by(Contents[?contains(Key, 'gfx94X')], &LastModified)[-1].Key")
        KEY=${KEY//\"/}
        test -n "$KEY" || { echo "No gfx94X tarball found"; exit 1; }
        aws s3 cp "s3://therock-nightly-tarball/${KEY}" rocm.tar.gz --no-sign-request
        ls -lh rocm.tar.gz
        echo "Downloaded: ${KEY}"
        sudo mkdir -p /opt/rocm
        sudo tar -xf *.tar.gz -C /opt/rocm

    - uses: actions/checkout@v5
      with:
        sparse-checkout: projects/aqlprofile
        set-safe-directory: true

    - name: Install Latest ROCm LLVM for RHEL
      if: ${{ matrix.system.os == 'rhel-9.1' }}
      shell: bash
      working-directory: /tmp
      run: |
        sudo tee /etc/yum.repos.d/rocm.repo <<EOF
        [ROCm-7.0.0]
        name=ROCm7.0.0
        baseurl=https://repo.radeon.com/rocm/rhel9/7.0_rc1/main
        enabled=1
        priority=50
        gpgcheck=1
        gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key
        EOF
        sudo rm -rf /etc/yum.repos.d/RHEL-partners.repo
        sudo dnf clean all
        sudo dnf install -y git rocm-llvm-devel rocm-openmp-sdk

    - name: Install Latest ROCm LLVM for SLES
      if: ${{ matrix.system.os == 'sles-15.4' }}
      shell: bash
      working-directory: /tmp
      run: |
        sudo tee /etc/zypp/repos.d/rocm.repo <<EOF
        [ROCm-7.0.0]
        name=ROCm7.0.0
        baseurl=https://repo.radeon.com/rocm/zyp/7.0_rc1/main
        enabled=1
        gpgcheck=1
        gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key
        EOF
        sudo zypper --gpg-auto-import-keys refresh
        sudo zypper install -y git rocm-llvm-devel rocm-openmp-sdk

    - name: Install Latest ROCm
      shell: bash
      working-directory: /tmp
      run: |
        python3 -m pip install --upgrade pip pipx
        python3 -m pipx install awscli
        python3 -m pipx ensurepath
        source ~/.bashrc
        KEY=$(aws s3api list-objects-v2 \
          --bucket therock-nightly-tarball \
          --no-sign-request \
          --output json \
          --query "sort_by(Contents[?contains(Key, 'gfx94X')], &LastModified)[-1].Key")
        KEY=${KEY//\"/}
        test -n "$KEY" || { echo "No gfx94X tarball found"; exit 1; }
        aws s3 cp "s3://therock-nightly-tarball/${KEY}" rocm.tar.gz --no-sign-request
        ls -lh rocm.tar.gz
        echo "Downloaded: ${KEY}"
        sudo tar -xf *.tar.gz -C /opt/rocm-7.0.0
        sudo ln -s /opt/rocm-7.0.0 /opt/rocm

    - name: Install requirements
      timeout-minutes: 10
      shell: bash
      run: |
        git config --global --add safe.directory '*'
        python3 -m pipx install cmake
        python3 -m pipx ensurepath
        source ~/.bashrc

    - name: List Files
      shell: bash
      run: |
        python3 -m pipx ensurepath
        source ~/.bashrc
        echo "PATH: ${PATH}"
        echo "LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}"
        which-realpath() { echo -e "\n$1 resolves to $(realpath $(which $1))"; echo "$($(which $1) --version &> /dev/stdout | head -n 1)"; }
        for i in python3 git cmake ctest gcc g++ gcov; do which-realpath $i; done
        cat /opt/rocm/.info/version
        ls -la
        pwd

    - name: Special Requirements
      shell: bash
      run: |
          echo 'CMAKE_HIP_PLATFORM=amd' >> $GITHUB_ENV
          echo 'HIP_PLATFORM=amd' >> $GITHUB_ENV
          echo 'HIP_RUNTIME=rocclr' >> $GITHUB_ENV
          echo 'HIP_COMPILER=amdclang++' >> $GITHUB_ENV
          echo 'LLVM_PATH=/opt/rocm/llvm' >> $GITHUB_ENV
          echo 'CMAKE_PREFIX_PATH=/opt/rocm' >> $GITHUB_ENV

    - name: Configure, Build, and Test
      timeout-minutes: 30
      shell: bash
      run:
        python3 -m pipx ensurepath; source ~/.bashrc;
        PATH=~/.local/bin:/opt/rocm/bin:$PATH
        LD_LIBRARY_PATH=$(pwd)/build:/opt/rocm/lib:$LD_LIBRARY_PATH
        ctest --output-on-failure -VV -DCTEST_SOURCE_DIRECTORY="$(pwd)"
          -DCTEST_BINARY_DIRECTORY="$(pwd)/build" -DAQLPROFILE_BUILD_NUM_JOBS="16" -DCTEST_SITE="linux-mi325-1gpu-ossci-rocm"
          -DCTEST_BUILD_NAME=PR_${{ github.ref_name }}_${{ github.repository }}-${{ matrix.system.os }}-${{ matrix.system.gpu }}-core
          -DCMAKE_CTEST_ARGUMENTS=""
          -DAQLPROFILE_BUILD_TESTS=ON
          -DAQLPROFILE_EXTRA_CONFIGURE_ARGS=""
          -S $(pwd)/projects/aqlprofile/dashboard.cmake
